/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminTreatmentsRouteImport } from './routes/admin.treatments'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminPostersRouteImport } from './routes/admin.posters'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreatmentsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TreatmentsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTreatmentsRoute = AdminTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostersRoute = AdminPostersRouteImport.update({
  id: '/posters',
  path: '/posters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/treatments'
    | '/admin/appointments'
    | '/admin/blogs'
    | '/admin/gallery'
    | '/admin/patients'
    | '/admin/posters'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/treatments'
    | '/admin/videos'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/admin/'
    | '/blog/'
    | '/treatments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/admin/appointments'
    | '/admin/blogs'
    | '/admin/gallery'
    | '/admin/patients'
    | '/admin/posters'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/treatments'
    | '/admin/videos'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/admin'
    | '/blog'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/treatments'
    | '/admin/appointments'
    | '/admin/blogs'
    | '/admin/gallery'
    | '/admin/patients'
    | '/admin/posters'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/treatments'
    | '/admin/videos'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/admin/'
    | '/blog/'
    | '/treatments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ReviewsRoute: typeof ReviewsRoute
  TreatmentsRoute: typeof TreatmentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/treatments': {
      id: '/admin/treatments'
      path: '/treatments'
      fullPath: '/admin/treatments'
      preLoaderRoute: typeof AdminTreatmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posters': {
      id: '/admin/posters'
      path: '/posters'
      fullPath: '/admin/posters'
      preLoaderRoute: typeof AdminPostersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPostersRoute: typeof AdminPostersRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTreatmentsRoute: typeof AdminTreatmentsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPostersRoute: AdminPostersRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTreatmentsRoute: AdminTreatmentsRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface TreatmentsRouteChildren {
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
}

const TreatmentsRouteChildren: TreatmentsRouteChildren = {
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
}

const TreatmentsRouteWithChildren = TreatmentsRoute._addFileChildren(
  TreatmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ReviewsRoute: ReviewsRoute,
  TreatmentsRoute: TreatmentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
